# Generated by Django 3.0.8 on 2020-07-18 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_visitdatabase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.RemoveField(
            model_name='openhour',
            name='name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='market',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='visitdatabase',
            name='name',
        ),
        migrations.RemoveField(
            model_name='visitorecord',
            name='markets',
        ),
        migrations.RemoveField(
            model_name='visitorecord',
            name='user',
        ),
        migrations.DeleteModel(
            name='Market',
        ),
        migrations.DeleteModel(
            name='Openhour',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='VisitDatabase',
        ),
        migrations.DeleteModel(
            name='VisitoRecord',
        ),
    ]
