# Generated by Django 3.0.8 on 2020-07-18 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_visitdatabase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-pk']},
        ),
    ]
