# Generated by Django 3.0.8 on 2020-07-17 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_visitdatabase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='visitorecord',
            old_name='user',
            new_name='user_id',
        ),
    ]
